//! Propositional formulas and their semantics.
//!
//! Mirrors AFP `Propositional_Proof_Systems`: `Formulas.thy` (datatype,
//! derived connectives) and `Sema.thy` (`formula_semantics`, entailment,
//! `sat`); `biimp` is from `Tseytin.thy`.
use vstd::prelude::*;

verus! {

/// `datatype 'a formula = Atom 'a | Bot | Not | And | Or | Imp`
pub enum Formula<A> {
    Atom(A),
    Bot,
    Not(Box<Formula<A>>),
    And(Box<Formula<A>>, Box<Formula<A>>),
    Or(Box<Formula<A>>, Box<Formula<A>>),
    Imp(Box<Formula<A>>, Box<Formula<A>>),
}

/// `atoms` (generated by the datatype declaration)
pub open spec fn atoms<A>(f: Formula<A>) -> Set<A>
    decreases f,
{
    match f {
        Formula::Atom(k) => Set::empty().insert(k),
        Formula::Bot => Set::empty(),
        Formula::Not(g) => atoms(*g),
        Formula::And(g, h) | Formula::Or(g, h) | Formula::Imp(g, h) => atoms(*g).union(atoms(*h)),
    }
}

/// `⊤ ≡ ⊥ → ⊥` (`Top`)
pub open spec fn top<A>() -> Formula<A> {
    Formula::Imp(Box::new(Formula::Bot), Box::new(Formula::Bot))
}

/// `F ↔ G ≡ (F → G) ∧ (G → F)` (`biimp`, `Tseytin.thy`)
pub open spec fn biimp<A>(f: Formula<A>, g: Formula<A>) -> Formula<A> {
    Formula::And(
        Box::new(Formula::Imp(Box::new(f), Box::new(g))),
        Box::new(Formula::Imp(Box::new(g), Box::new(f))),
    )
}

/// `⋀[] = ¬⊥`, `⋀(F#Fs) = F ∧ ⋀Fs` (`BigAnd`)
pub open spec fn big_and<A>(fs: Seq<Formula<A>>) -> Formula<A>
    decreases fs.len(),
{
    if fs.len() == 0 {
        Formula::Not(Box::new(Formula::Bot))
    } else {
        Formula::And(Box::new(fs[0]), Box::new(big_and(fs.drop_first())))
    }
}

/// `⋁[] = ⊥`, `⋁(F#Fs) = F ∨ ⋁Fs` (`BigOr`)
pub open spec fn big_or<A>(fs: Seq<Formula<A>>) -> Formula<A>
    decreases fs.len(),
{
    if fs.len() == 0 {
        Formula::Bot
    } else {
        Formula::Or(Box::new(fs[0]), Box::new(big_or(fs.drop_first())))
    }
}

/// `formula_semantics 𝒜 F` (`𝒜 ⊨ F`); a valuation is `'a ⇒ bool`.
pub open spec fn formula_semantics<A>(v: spec_fn(A) -> bool, f: Formula<A>) -> bool
    decreases f,
{
    match f {
        Formula::Atom(k) => v(k),
        Formula::Bot => false,
        Formula::Not(g) => !formula_semantics(v, *g),
        Formula::And(g, h) => formula_semantics(v, *g) && formula_semantics(v, *h),
        Formula::Or(g, h) => formula_semantics(v, *g) || formula_semantics(v, *h),
        Formula::Imp(g, h) => formula_semantics(v, *g) ==> formula_semantics(v, *h),
    }
}

/// `Γ ⊫ F ≡ ∀𝒜. (∀G ∈ Γ. 𝒜 ⊨ G) ⟶ 𝒜 ⊨ F` (`entailment`). Γ is a finite set
/// here; every use in the MLTL development is finite.
pub open spec fn entailment<A>(gamma: Set<Formula<A>>, f: Formula<A>) -> bool {
    forall|v: spec_fn(A) -> bool|
        (forall|g: Formula<A>| #[trigger] gamma.contains(g) ==> formula_semantics(v, g))
            ==> #[trigger] formula_semantics(v, f)
}

/// `sat S ≡ ∃𝒜. ∀F ∈ S. 𝒜 ⊨ F`
pub open spec fn sat<A>(s: Set<Formula<A>>) -> bool {
    exists|v: spec_fn(A) -> bool| #[trigger] models_set(v, s)
}

/// `∀F ∈ S. 𝒜 ⊨ F` (the body of `sat`)
pub open spec fn models_set<A>(v: spec_fn(A) -> bool, s: Set<Formula<A>>) -> bool {
    forall|g: Formula<A>| #[trigger] s.contains(g) ==> formula_semantics(v, g)
}

/// `top_semantics`: `𝒜 ⊨ ⊤`
pub proof fn top_semantics<A>(v: spec_fn(A) -> bool)
    ensures
        formula_semantics(v, top::<A>()),
{
}

/// `biimp_simp`: `𝒜 ⊨ F ↔ G ⟷ (𝒜 ⊨ F ⟷ 𝒜 ⊨ G)`
pub proof fn biimp_semantics<A>(v: spec_fn(A) -> bool, f: Formula<A>, g: Formula<A>)
    ensures
        formula_semantics(v, biimp(f, g)) == (formula_semantics(v, f) == formula_semantics(v, g)),
{
    reveal_with_fuel(formula_semantics, 3);
}

/// `BigAnd_semantics`: `𝒜 ⊨ ⋀F ⟷ (∀f ∈ set F. 𝒜 ⊨ f)`
pub proof fn big_and_semantics<A>(v: spec_fn(A) -> bool, fs: Seq<Formula<A>>)
    ensures
        formula_semantics(v, big_and(fs)) == (forall|i: int|
            0 <= i < fs.len() ==> formula_semantics(v, #[trigger] fs[i])),
    decreases fs.len(),
{
    reveal_with_fuel(formula_semantics, 2);
    if fs.len() > 0 {
        big_and_semantics(v, fs.drop_first());
        if formula_semantics(v, big_and(fs)) {
            assert forall|i: int| 0 <= i < fs.len() implies formula_semantics(v, #[trigger] fs[i]) by {
                if i > 0 {
                    assert(fs[i] == fs.drop_first()[i - 1]);
                }
            }
        } else if forall|i: int| 0 <= i < fs.len() ==> formula_semantics(v, #[trigger] fs[i]) {
            assert(formula_semantics(v, fs[0]));
            assert forall|i: int| 0 <= i < fs.drop_first().len() implies formula_semantics(
                v,
                #[trigger] fs.drop_first()[i],
            ) by {
                assert(fs.drop_first()[i] == fs[i + 1]);
            }
        }
    }
}

/// `BigOr_semantics`: `𝒜 ⊨ ⋁F ⟷ (∃f ∈ set F. 𝒜 ⊨ f)`
pub proof fn big_or_semantics<A>(v: spec_fn(A) -> bool, fs: Seq<Formula<A>>)
    ensures
        formula_semantics(v, big_or(fs)) == (exists|i: int|
            0 <= i < fs.len() && formula_semantics(v, #[trigger] fs[i])),
    decreases fs.len(),
{
    if fs.len() > 0 {
        big_or_semantics(v, fs.drop_first());
        if formula_semantics(v, big_or(fs)) {
            if !formula_semantics(v, fs[0]) {
                let i = choose|i: int|
                    0 <= i < fs.drop_first().len() && formula_semantics(v, #[trigger] fs.drop_first()[i]);
                assert(fs.drop_first()[i] == fs[i + 1]);
            }
        } else if exists|i: int| 0 <= i < fs.len() && formula_semantics(v, #[trigger] fs[i]) {
            let i = choose|i: int| 0 <= i < fs.len() && formula_semantics(v, #[trigger] fs[i]);
            assert(i != 0);
            assert(fs.drop_first()[i - 1] == fs[i]);
        }
    }
}

/// `entail_sat`: `Γ ⊫ ⊥ ⟷ ¬ sat Γ`
pub proof fn entail_sat<A>(gamma: Set<Formula<A>>)
    ensures
        entailment(gamma, Formula::Bot) == !sat(gamma),
{
    if sat(gamma) {
        let v = choose|v: spec_fn(A) -> bool| #[trigger] models_set(v, gamma);
        assert(!formula_semantics(v, Formula::<A>::Bot));
    }
    if !entailment(gamma, Formula::Bot) {
        let v = choose|v: spec_fn(A) -> bool|
            !((forall|g: Formula<A>| #[trigger] gamma.contains(g) ==> formula_semantics(v, g))
                ==> #[trigger] formula_semantics(v, Formula::<A>::Bot));
        assert(models_set(v, gamma));
    }
}

} // verus!
