//! MLTL syntax and semantics.
//!
//! Mirrors AFP `Mission_Time_LTL`, theory `MLTL_Encoding.thy`, definition by
//! definition. Correspondence table: agent-docs/correspondence/mission-time-ltl.md.
use vstd::prelude::*;

verus! {

broadcast use vstd::set::group_set_lemmas;

// ---------------------------------------------------------------------------
// Syntax  (Isabelle: datatype 'a mltl)
// ---------------------------------------------------------------------------

/// An MLTL formula over atoms of type `A`.
///
/// Interval bounds are `usize` (Isabelle: `nat`); specs read them as `nat`.
/// Variant order and argument order match the Isabelle constructors, e.g.
/// `Until(φ, a, b, ψ)` is `Until_mltl φ a b ψ` (`φ U[a,b] ψ`).
pub enum Mltl<A> {
    /// `True_mltl`
    True,
    /// `False_mltl`
    False,
    /// `Prop_mltl p`
    Prop(A),
    /// `Not_mltl φ`
    Not(Box<Mltl<A>>),
    /// `And_mltl φ ψ`
    And(Box<Mltl<A>>, Box<Mltl<A>>),
    /// `Or_mltl φ ψ`
    Or(Box<Mltl<A>>, Box<Mltl<A>>),
    /// `Future_mltl a b φ`  (`F[a,b] φ`)
    Future(usize, usize, Box<Mltl<A>>),
    /// `Global_mltl a b φ`  (`G[a,b] φ`)
    Global(usize, usize, Box<Mltl<A>>),
    /// `Until_mltl φ a b ψ`  (`φ U[a,b] ψ`)
    Until(Box<Mltl<A>>, usize, usize, Box<Mltl<A>>),
    /// `Release_mltl φ a b ψ`  (`φ R[a,b] ψ`)
    Release(Box<Mltl<A>>, usize, usize, Box<Mltl<A>>),
}

/// `Implies_mltl φ ψ ≡ Not_mltl φ Or_mltl ψ`
pub open spec fn implies_mltl<A>(phi: Mltl<A>, psi: Mltl<A>) -> Mltl<A> {
    Mltl::Or(Box::new(Mltl::Not(Box::new(phi))), Box::new(psi))
}

/// `Iff_mltl φ ψ ≡ (φ Implies_mltl ψ) And_mltl (ψ Implies_mltl φ)`
pub open spec fn iff_mltl<A>(phi: Mltl<A>, psi: Mltl<A>) -> Mltl<A> {
    Mltl::And(Box::new(implies_mltl(phi, psi)), Box::new(implies_mltl(psi, phi)))
}

/// `atoms_mltl`: the set of atoms occurring in a formula (generated by the
/// Isabelle datatype declaration).
pub open spec fn atoms_mltl<A>(f: Mltl<A>) -> Set<A>
    decreases f,
{
    match f {
        Mltl::True | Mltl::False => Set::empty(),
        Mltl::Prop(p) => Set::empty().insert(p),
        Mltl::Not(g) | Mltl::Future(_, _, g) | Mltl::Global(_, _, g) => atoms_mltl(*g),
        Mltl::And(g, h) | Mltl::Or(g, h) | Mltl::Until(g, _, _, h) | Mltl::Release(g, _, _, h) =>
            atoms_mltl(*g).union(atoms_mltl(*h)),
    }
}

/// Isabelle's generated `size` on `'a mltl`: one per constructor node, leaves
/// included; interval bounds do not count. (Checked against Isabelle2025-2:
/// `size (U T 3 4 (P 0)) = 3`, `size (F 3 4 (P 0)) = 2`.)
pub open spec fn size_mltl<A>(f: Mltl<A>) -> nat
    decreases f,
{
    match f {
        Mltl::True | Mltl::False | Mltl::Prop(_) => 1,
        Mltl::Not(g) | Mltl::Future(_, _, g) | Mltl::Global(_, _, g) => 1 + size_mltl(*g),
        Mltl::And(g, h) | Mltl::Or(g, h) | Mltl::Until(g, _, _, h) | Mltl::Release(g, _, _, h) =>
            1 + size_mltl(*g) + size_mltl(*h),
    }
}

// ---------------------------------------------------------------------------
// List / nat helpers with Isabelle's (total) meaning
// ---------------------------------------------------------------------------

/// Isabelle `drop i π`: total; `[]` when `i > length π`.
pub open spec fn drop<T>(pi: Seq<T>, i: nat) -> Seq<T> {
    if i <= pi.len() {
        pi.skip(i as int)
    } else {
        Seq::empty()
    }
}

/// Isabelle `take i π`: total; `π` when `i > length π`.
pub open spec fn take<T>(pi: Seq<T>, i: nat) -> Seq<T> {
    if i <= pi.len() {
        pi.take(i as int)
    } else {
        pi
    }
}

/// Isabelle `x - y` on `nat`: truncates at 0.
pub open spec fn nat_sub(x: nat, y: nat) -> nat {
    if x >= y {
        (x - y) as nat
    } else {
        0
    }
}

pub proof fn lemma_drop_len<T>(pi: Seq<T>, i: nat)
    ensures
        drop(pi, i).len() == nat_sub(pi.len(), i),
{
}

/// `drop i (drop s π) = drop (s + i) π`
pub proof fn lemma_drop_drop<T>(pi: Seq<T>, s: nat, i: nat)
    ensures
        drop(drop(pi, s), i) == drop(pi, s + i),
{
    if s + i <= pi.len() {
        assert(drop(drop(pi, s), i) =~= drop(pi, s + i));
    } else {
        assert(drop(drop(pi, s), i) =~= Seq::<T>::empty());
        assert(drop(pi, s + i) =~= Seq::<T>::empty());
    }
}

/// All suffixes past the end are `[]`.
pub proof fn lemma_drop_past_end<T>(pi: Seq<T>, i: nat)
    requires
        i >= pi.len(),
    ensures
        drop(pi, i) == drop(pi, pi.len()),
        drop(pi, i) == Seq::<T>::empty(),
{
    assert(drop(pi, pi.len()) =~= Seq::<T>::empty());
}

pub proof fn lemma_drop_zero<T>(pi: Seq<T>)
    ensures
        drop(pi, 0) == pi,
{
    assert(drop(pi, 0) =~= pi);
}

// ---------------------------------------------------------------------------
// Semantics  (Isabelle: primrec semantics_mltl, notation π ⊨_m φ)
// ---------------------------------------------------------------------------

/// `semantics_mltl π φ`: the finite trace `π` (a list of states, each the
/// set of atoms true at that step) satisfies `φ`.
///
/// States are finite sets (`Set<A>`), whereas Isabelle's `'a set` may be
/// infinite. Deliberate: MLTL is a finite logic (D16).
///
/// Case for case with `MLTL_Encoding.thy`. Note (Verus): quantifiers here have
/// no explicit triggers on purpose; Verus picks `drop(pi, i)`. Proofs that
/// quantify over these terms should trigger on `drop(pi, k)` too — see
/// agent-docs/verification/verus-notes.md.
pub open spec fn semantics_mltl<A>(pi: Seq<Set<A>>, f: Mltl<A>) -> bool
    decreases f,
{
    match f {
        Mltl::True => true,
        Mltl::False => false,
        Mltl::Prop(q) => pi.len() != 0 && pi[0].contains(q),
        Mltl::Not(phi) => !semantics_mltl(pi, *phi),
        Mltl::And(phi, psi) => semantics_mltl(pi, *phi) && semantics_mltl(pi, *psi),
        Mltl::Or(phi, psi) => semantics_mltl(pi, *phi) || semantics_mltl(pi, *psi),
        Mltl::Future(a, b, phi) => a <= b && pi.len() > a
            && exists|i: nat| (a <= i && i <= b) && semantics_mltl(drop(pi, i), *phi),
        Mltl::Global(a, b, phi) => a <= b && (pi.len() <= a
            || forall|i: nat| (a <= i && i <= b) ==> semantics_mltl(drop(pi, i), *phi)),
        Mltl::Until(phi, a, b, psi) => a <= b && pi.len() > a
            && exists|i: nat| (a <= i && i <= b) && (semantics_mltl(drop(pi, i), *psi)
                && forall|j: nat| (j >= a && j < i) ==> semantics_mltl(drop(pi, j), *phi)),
        Mltl::Release(phi, a, b, psi) => a <= b && (pi.len() <= a
            || (forall|i: nat| (a <= i && i <= b) ==> semantics_mltl(drop(pi, i), *psi))
            || exists|j: nat| (j >= a && j <= nat_sub(b as nat, 1)) && semantics_mltl(drop(pi, j), *phi)
                && forall|k: nat| (a <= k && k <= j) ==> semantics_mltl(drop(pi, k), *psi)),
    }
}

// ---------------------------------------------------------------------------
// Examples  (MLTL_Encoding.thy, subsubsection Examples; atoms are nat)
// ---------------------------------------------------------------------------

/// `[{0}] ⊨_m Not_mltl (F[0,2] Prop 0) = False`
pub proof fn example_not_future()
    ensures
        !semantics_mltl(
            seq![Set::empty().insert(0nat)],
            Mltl::Not(Box::new(Mltl::Future(0, 2, Box::new(Mltl::Prop(0nat))))),
        ),
{
    reveal_with_fuel(semantics_mltl, 3);
    let pi = seq![Set::empty().insert(0nat)];
    lemma_drop_zero(pi);
    assert(semantics_mltl(drop(pi, 0), Mltl::Prop(0nat)));
}

/// `[{0}] ⊨_m F[0,2] (Not_mltl Prop 0) = True`
pub proof fn example_future_not()
    ensures
        semantics_mltl(
            seq![Set::empty().insert(0nat)],
            Mltl::Future(0, 2, Box::new(Mltl::Not(Box::new(Mltl::Prop(0nat))))),
        ),
{
    reveal_with_fuel(semantics_mltl, 3);
    let pi = seq![Set::empty().insert(0nat)];
    assert(pi.len() == 1);
    assert(drop(pi, 1).len() == 0);
    assert(semantics_mltl(drop(pi, 1), Mltl::Not(Box::new(Mltl::Prop(0nat)))));
}

/// `[{0}] ⊨_m G[0,2] Prop 0 = False`
pub proof fn example_global()
    ensures
        !semantics_mltl(
            seq![Set::empty().insert(0nat)],
            Mltl::Global(0, 2, Box::new(Mltl::Prop(0nat))),
        ),
{
    reveal_with_fuel(semantics_mltl, 3);
    let pi = seq![Set::empty().insert(0nat)];
    assert(pi.len() == 1);
    assert(drop(pi, 1).len() == 0);
    assert(!semantics_mltl(drop(pi, 1), Mltl::Prop(0nat)));
}

// ---------------------------------------------------------------------------
// Sanity checks (not in Isabelle): exercise the Until/Release cases
// ---------------------------------------------------------------------------

/// `[{1}, {0}] ⊨_m (Prop 1) U[0,1] (Prop 0)`
pub proof fn sanity_until()
    ensures
        semantics_mltl(
            seq![Set::empty().insert(1nat), Set::empty().insert(0nat)],
            Mltl::Until(Box::new(Mltl::Prop(1nat)), 0, 1, Box::new(Mltl::Prop(0nat))),
        ),
{
    reveal_with_fuel(semantics_mltl, 2);
    let pi = seq![Set::empty().insert(1nat), Set::empty().insert(0nat)];
    lemma_drop_zero(pi);
    assert(drop(pi, 1) =~= seq![Set::empty().insert(0nat)]);
    assert(semantics_mltl(drop(pi, 1), Mltl::Prop(0nat)));
    assert(semantics_mltl(drop(pi, 0), Mltl::Prop(1nat)));
}

/// `b - 1` truncates: `[{0}] ⊨_m (Prop 0) R[0,0] (Prop 0)` holds, and
/// `[{}] ⊨_m (Prop 0) R[0,0] (Prop 0)` does not.
pub proof fn sanity_release_zero_bound()
    ensures
        semantics_mltl(
            seq![Set::empty().insert(0nat)],
            Mltl::Release(Box::new(Mltl::Prop(0nat)), 0, 0, Box::new(Mltl::Prop(0nat))),
        ),
        !semantics_mltl(
            seq![Set::<nat>::empty()],
            Mltl::Release(Box::new(Mltl::Prop(0nat)), 0, 0, Box::new(Mltl::Prop(0nat))),
        ),
{
    reveal_with_fuel(semantics_mltl, 2);
    let pi = seq![Set::empty().insert(0nat)];
    lemma_drop_zero(pi);
    assert(semantics_mltl(drop(pi, 0), Mltl::Prop(0nat)));
    let e = seq![Set::<nat>::empty()];
    lemma_drop_zero(e);
    assert(!semantics_mltl(drop(e, 0), Mltl::Prop(0nat)));
}

// ---------------------------------------------------------------------------
// Executable copy and equality (usize atoms, D19)
// ---------------------------------------------------------------------------

/// Executable deep copy: `clone_mltl(f) == *f`.
pub fn clone_mltl(f: &Mltl<usize>) -> (r: Mltl<usize>)
    ensures
        r == *f,
    decreases f,
{
    match f {
        Mltl::True => Mltl::True,
        Mltl::False => Mltl::False,
        Mltl::Prop(p) => Mltl::Prop(*p),
        Mltl::Not(g) => Mltl::Not(Box::new(clone_mltl(g))),
        Mltl::And(g, h) => Mltl::And(Box::new(clone_mltl(g)), Box::new(clone_mltl(h))),
        Mltl::Or(g, h) => Mltl::Or(Box::new(clone_mltl(g)), Box::new(clone_mltl(h))),
        Mltl::Future(a, b, g) => Mltl::Future(*a, *b, Box::new(clone_mltl(g))),
        Mltl::Global(a, b, g) => Mltl::Global(*a, *b, Box::new(clone_mltl(g))),
        Mltl::Until(g, a, b, h) => Mltl::Until(Box::new(clone_mltl(g)), *a, *b, Box::new(clone_mltl(h))),
        Mltl::Release(g, a, b, h) => Mltl::Release(Box::new(clone_mltl(g)), *a, *b, Box::new(clone_mltl(h))),
    }
}

/// Executable structural equality (Isabelle `=` on `'a mltl`):
/// `eq_mltl(f, g) == (*f == *g)`.
pub fn eq_mltl(f: &Mltl<usize>, g: &Mltl<usize>) -> (r: bool)
    ensures
        r == (*f == *g),
    decreases f,
{
    match (f, g) {
        (Mltl::True, Mltl::True) => true,
        (Mltl::False, Mltl::False) => true,
        (Mltl::Prop(p), Mltl::Prop(q)) => *p == *q,
        (Mltl::Not(f1), Mltl::Not(g1)) => eq_mltl(f1, g1),
        (Mltl::And(f1, f2), Mltl::And(g1, g2)) => eq_mltl(f1, g1) && eq_mltl(f2, g2),
        (Mltl::Or(f1, f2), Mltl::Or(g1, g2)) => eq_mltl(f1, g1) && eq_mltl(f2, g2),
        (Mltl::Future(a, b, f1), Mltl::Future(c, d, g1)) => *a == *c && *b == *d && eq_mltl(f1, g1),
        (Mltl::Global(a, b, f1), Mltl::Global(c, d, g1)) => *a == *c && *b == *d && eq_mltl(f1, g1),
        (Mltl::Until(f1, a, b, f2), Mltl::Until(g1, c, d, g2)) =>
            *a == *c && *b == *d && eq_mltl(f1, g1) && eq_mltl(f2, g2),
        (Mltl::Release(f1, a, b, f2), Mltl::Release(g1, c, d, g2)) =>
            *a == *c && *b == *d && eq_mltl(f1, g1) && eq_mltl(f2, g2),
        _ => false,
    }
}

} // verus!
